### ISSUE TITLE
jpeg dependency won't build via t2-compiler

### ISSUE THREAD

**Issue by rwaldron** [tessel/node-audiovideo#4]
I realize this is likely _not_ the right place for this to be filed, but since the version of `jpeg` in use is actually just a branch on a fork, with no "issues" tracker of its own, I'm not sure where else to put this. 

---

See: https://github.com/tessel/node-audiovideo/blob/master/package.json#L15

With the latest version of the `t2-compiler` repo (supports git): 

```
./compile.sh git+https://github.com/tcr/node-jpeg.git#tcr-nan2
```

Elided result: 

```
... (everything is fine until we get here)

gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Debug', '-C', 'build' ]
  CXX(target) Debug/obj.target/jpeg/src/common.o
  CXX(target) Debug/obj.target/jpeg/src/jpeg_encoder.o
In file included from ../src/jpeg_encoder.cpp:1:0:
../src/jpeg_encoder.h:6:21: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
                     ^
compilation terminated.
make: *** [Debug/obj.target/jpeg/src/jpeg_encoder.o] Error 1
make: Leaving directory `/work/binary-module/package/build'

... (then it backs out)
```

**Comment by rwaldron** [comment]
Maybe useful: https://github.com/kevin-roark/socket.io-computer/issues/11

> Finally, installing all of its dependencies by running sudo apt-get -y install libcairo2-dev libpango1.0-dev > libgif-dev build-essential g++
> 
> You will also need libjpeg9 and libjpeg9-dev which are available in the Debian repositories: 
> https://packages.debian.org/search?keywords=libjpeg9

**Comment by tcr** [comment]
Should be fixed by https://github.com/tessel/openwrt-tessel/commit/07d953e7e7697e20026ef55f477a1dc33bbb25c8.

**Comment by rwaldron** [comment]
Ah, fantastic
