### ISSUE TITLE
Drop non-existant support for OSX

### ISSUE THREAD

**Issue by rwaldron** [tessel/node-audiovideo#7]
It's not implemented and as a result misleading: 

``` js
var av = require("audiovideo");
av.acquireCamera(function(err, acquired) {
  console.log(acquired);
});
```

```
$ node capture.js
OSXCamera {}
```

Note: there is no `cam` property, because there is nothing making one:  https://github.com/tessel/node-audiovideo/blob/master/index.js#L7-L8

**Comment by tcr** [comment]
@rwaldron It differs in its internal properties, but `npm test` shows it does work on OS X so far:

```
av.acquireCamera(function (err, camera) {
  imagesize(camera.captureShot('jpeg'), function (err, res) {
    assert.ok(err == null);
    assert.ok(res.format == 'jpeg');
    assert.ok(res.width > 0);
    assert.ok(res.height > 0);
    console.error('passed:', res);
  });
})
```

OS X just implements a simple stream for now.

**Comment by rwaldron** [comment]
This is no longer an issue in the current development branch
